# Generated by Django 5.0 on 2025-11-10 10:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10, verbose_name='Niveau de difficulté')),
                ('description_file', models.FileField(upload_to='challenges/descriptions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'md'])], verbose_name='Fichier description (markdown)')),
                ('template_file', models.FileField(upload_to='challenges/templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='Fichier template (.py)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='challenges/inputs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])], verbose_name='Fichier input (.txt)')),
                ('output_file', models.FileField(upload_to='challenges/outputs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])], verbose_name='Fichier output (.txt)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_sample', models.BooleanField(default=False, verbose_name='Exemple visible')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api.challenge')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'ordering': ['order'],
            },
        ),
    ]
