# Generated by Django 5.0 on 2025-11-11 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='xp_reward',
            field=models.IntegerField(default=100, verbose_name='Points XP'),
        ),
        migrations.CreateModel(
            name='UserChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('completion_time', models.IntegerField(blank=True, null=True, verbose_name='Temps de résolution (secondes)')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP gagné')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='api.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative de Challenge',
                'verbose_name_plural': 'Tentatives de Challenges',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
