# Generated by Django 5.0 on 2025-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_challenge_xp_reward_userchallengeattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='participants_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de participants'),
        ),
    ]
