# Generated by Django 5.0 on 2025-11-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_team_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
