# Generated by Django 5.0 on 2025-11-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usercodesave'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='xp_required',
            field=models.IntegerField(default=0, verbose_name='XP minimum requis pour valider la soumission'),
        ),
    ]
