# Generated by Django 5.0 on 2025-11-19 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_challenge_xp_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='description_img',
            field=models.ImageField(blank=True, null=True, upload_to='challenges/descriptions/images/', verbose_name='Image de description'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='description_pdf',
            field=models.FileField(blank=True, null=True, upload_to='challenges/descriptions/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Description en PDF'),
        ),
    ]
