# Generated by Django 5.0 on 2025-11-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_challenge_description_img_challenge_description_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='invited_user',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamInvitation',
        ),
    ]
