# Generated by Django 5.0 on 2026-05-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_challenge_description_file_and_more'),
        ('api', '0010_testcase_xp_reward'),
    ]

    operations = [
    ]
