# Generated by Django 5.0 on 2026-05-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20260506_2112'),
        ('api', '0011_remove_challenge_xp_reward'),
    ]

    operations = [
    ]
