# Generated by Django 5.0 on 2026-05-06 18:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260506_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchallengeattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fichier description (markdown)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image de description'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Description PDF'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='template_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fichier template (.py)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='xp_required',
            field=models.IntegerField(default=0, verbose_name='XP minimum requis'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fichier input (.txt)'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fichier output (.txt)'),
        ),
        migrations.AlterField(
            model_name='userchallengeattempt',
            name='attempts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userchallengeattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userchallengeattempt',
            name='completion_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userchallengeattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userchallengeattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='userchallengeattempt',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
    ]
