# Generated by Django 5.0 on 2025-11-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-total_xp', 'username'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='challenges_joined',
            field=models.IntegerField(default=0, verbose_name='Nombre de challenges rejoints'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_xp',
            field=models.IntegerField(default=0, verbose_name='XP total'),
        ),
    ]
