# Generated by Django 5.0 on 2025-11-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_challenges_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='filiere',
        ),
        migrations.AddField(
            model_name='user',
            name='classe',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], default='L1', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='parcours',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Network Administration', 'Network Administration'), ('Common Core', 'Common Core')], default='Common Core', max_length=50),
        ),
    ]
