# Generated by Django 5.0 on 2025-11-10 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('abandoned', 'Abandonné')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Points obtenus')),
                ('total_points', models.IntegerField(default=0, verbose_name='Points totaux possibles')),
                ('total_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Temps total (secondes)')),
                ('submission_count', models.IntegerField(default=0, verbose_name='Nombre de soumissions')),
                ('last_submitted_code', models.TextField(blank=True, verbose_name='Dernier code soumis')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.challenge', verbose_name='Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tentative de Challenge',
                'verbose_name_plural': 'Tentatives de Challenges',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, verbose_name='Points totaux')),
                ('challenges_completed', models.IntegerField(default=0, verbose_name='Challenges terminés')),
                ('challenges_attempted', models.IntegerField(default=0, verbose_name='Challenges tentés')),
                ('global_rank', models.IntegerField(blank=True, null=True, verbose_name='Rang global')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Classement',
                'verbose_name_plural': 'Classements',
                'ordering': ['-total_points', 'challenges_completed'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Code soumis')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Solution correcte')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Points obtenus')),
                ('passed_tests', models.IntegerField(default=0, verbose_name='Tests réussis')),
                ('total_tests', models.IntegerField(default=0, verbose_name='Total de tests')),
                ('execution_time', models.FloatField(default=0, verbose_name="Temps d'exécution (secondes)")),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.challengeattempt', verbose_name='Tentative')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='challengeattempt',
            index=models.Index(fields=['challenge', '-points_earned', 'total_time_seconds'], name='submissions_challen_d327fc_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeattempt',
            index=models.Index(fields=['user', 'status'], name='submissions_user_id_c58289_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeattempt',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['attempt', '-submitted_at'], name='submissions_attempt_c7d9ae_idx'),
        ),
    ]
