# Generated by Django 5.0 on 2025-11-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_remove_teaminvitation_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('upcoming', 'À venir'), ('ongoing', 'En cours'), ('finished', 'Terminé')], default='upcoming', max_length=20, verbose_name='Statut')),
                ('nombre_team', models.IntegerField(default=0, verbose_name="Nombre d'équipes")),
                ('type', models.CharField(choices=[('individual', 'Individuel'), ('team', 'Équipe')], default='team', max_length=20, verbose_name='Type de contest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenges', models.ManyToManyField(related_name='contests', to='api.challenge', verbose_name='Challenges')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('xp_total', models.IntegerField(default=0, verbose_name='XP total')),
                ('temps_total', models.IntegerField(default=0, verbose_name='Temps total (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capitaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitaine_teams', to=settings.AUTH_USER_MODEL, verbose_name='Capitaine')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='contests.contest', verbose_name='Contest')),
                ('membres', models.ManyToManyField(related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['-xp_total', 'temps_total'],
                'unique_together': {('contest', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_soumis', models.TextField(verbose_name='Code soumis')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP obtenue')),
                ('temps_soumission', models.IntegerField(default=0, verbose_name='Temps de soumission (secondes)')),
                ('tests_reussis', models.IntegerField(default=0, verbose_name='Nombre de tests réussis')),
                ('tests_total', models.IntegerField(default=0, verbose_name='Nombre total de tests')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to='api.challenge', verbose_name='Challenge')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Soumission Contest',
                'verbose_name_plural': 'Soumissions Contest',
                'ordering': ['-submitted_at'],
                'unique_together': {('equipe', 'challenge')},
            },
        ),
    ]
