# Generated by Django 5.0 on 2026-01-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_img',
            field=models.ImageField(blank=True, help_text='Image de couverture du contest', null=True, upload_to='contests/', verbose_name='Image du contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du contest', null=True, verbose_name='Description'),
        ),
    ]
