# Generated by Django 5.0 on 2026-02-03 06:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_contest_img_contest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_img',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image de couverture du contest', max_length=255, null=True, verbose_name='image'),
        ),
    ]
