# Generated by Django 5.0 on 2026-05-06 18:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_contest_contest_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_img',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image de couverture du contest', max_length=255, null=True, verbose_name='Image du contest'),
        ),
    ]
